# Generated by Django 4.2.23 on 2026-03-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
