# Generated by Django 4.2.23 on 2026-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
