# Generated by Django 4.2.23 on 2026-03-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
